language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_script:
  - cargo install --force cargo-audit
script:
  - cargo audit
  - cargo build --verbose
  - cargo test --verbose
