[package]
name = "did-i-github-today"
version = "0.1.0"
authors = ["Phil <PhilboBaggins@users.noreply.github.com>"]

[dependencies]
clap = "2.32.0"
json = "0.11.13"
reqwest = "0.8.7"
chrono = "0.4.5"
